### ISSUE TITLE
lua socket issue

### ISSUE THREAD

**Issue by 10der** [actboy168/vscode-lua-debug#21]
Hi!

after the upgrade, I have the issue with LUA socket

./libs/socket.lua':
	%1 is not a valid Win32 application.

**Comment by actboy168** [comment]
Please provide examples of reproduce.

**Comment by 10der** [comment]
Ok. just a momnet.

btw, why you change 
            "console": "utf8",
on
	    "consoleCoding": "utf8"
 
now I should walk on my all projects and change it. Ahhhg :)

**Comment by 10der** [comment]
sorry! 
can't reproduce.

``
`VS code - upgrade to actboy168.lua-debug-0.2.11 
run
./libs/socket.lua': %1 is not a valid Win32 application.
close VS code
run
ok!
```

IMHO it's VScode issue.

thank you so much and sorry.

**Comment by actboy168** [comment]
Because I added a new feature to choose the kind of console. Although it is not a mandatory standard, the reference to this feature in the vscode documentation uses the `console`. The official debuggers maintained by MS also use the same name, so I decided to respect it.

https://code.visualstudio.com/docs/editor/debugging

**Comment by 10der** [comment]
I was scared ;) when my all scripts lost print functionality.
thank you! got it!
